FROM nginx

VOLUME ["/var/www/html"]

ADD docker/reverseproxy/default.conf /etc/nginx/conf.d/default.conf
#ADD docker/reverseproxy/cert.pem /etc/nginx/conf.d/cert.pem
#ADD docker/reverseproxy/key.pem /etc/nginx/conf.d/key.pem
