FROM nginx

VOLUME ["/var/www/html"]

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
#ADD docker/nginx/cert.pem /etc/nginx/conf.d/cert.pem
#ADD docker/nginx/key.pem /etc/nginx/conf.d/key.pem
